package ru.itmo.se.is.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_JSON,
    PROCESSING_ERROR,
    NOT_FOUND,
    DELETION_CONFLICT,
    CONCURRENT_MODIFICATION,
    UNIQUE_CONSTRAINT_VIOLATION,
}
