package ru.itmo.se.is.shared.dto.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_JSON,
    NOT_FOUND,
    ENTITY_CONNECTED,
    CONCURRENT_MODIFICATION,
    ENTITY_ALREADY_EXISTS,
    INTERNAL_SERVER_ERROR,
    FILE_IMPORT_ERROR,
    IMPORT_DATA_VALIDATION
}
